import type {
  Account,
  Rep,
  Opportunity,
  AccountScore,
  Recommendation,
  RepAccountFit,
  ICPModel,
} from '@/types';

// ============================================================
// REPS
// ============================================================
export const mockReps: Rep[] = [
  {
    id: 'rep-001',
    org_id: 'org-001',
    crm_id: 'SF-U001',
    name: 'Sarah Chen',
    email: 'sarah.chen@acme.com',
    role: 'Account Executive',
    segment: 'enterprise',
    verticals: ['SaaS', 'FinTech'],
    territory: 'West',
    tenure_months: 36,
    ramp_status: 'veteran',
    active_account_count: 18,
    pipeline_value: 1_850_000,
    capacity_score: 42,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'rep-002',
    org_id: 'org-001',
    crm_id: 'SF-U002',
    name: 'Marcus Johnson',
    email: 'marcus.j@acme.com',
    role: 'Account Executive',
    segment: 'mid-market',
    verticals: ['Healthcare', 'Insurance'],
    territory: 'Central',
    tenure_months: 14,
    ramp_status: 'ramped',
    active_account_count: 24,
    pipeline_value: 920_000,
    capacity_score: 65,
    created_at: '2025-02-01T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'rep-003',
    org_id: 'org-001',
    crm_id: 'SF-U003',
    name: 'Priya Patel',
    email: 'priya.p@acme.com',
    role: 'Account Executive',
    segment: 'mid-market',
    verticals: ['SaaS', 'E-commerce'],
    territory: 'East',
    tenure_months: 8,
    ramp_status: 'ramping',
    active_account_count: 12,
    pipeline_value: 410_000,
    capacity_score: 82,
    created_at: '2025-08-15T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'rep-004',
    org_id: 'org-001',
    crm_id: 'SF-U004',
    name: 'David Kim',
    email: 'david.k@acme.com',
    role: 'Senior Account Executive',
    segment: 'enterprise',
    verticals: ['Manufacturing', 'Logistics'],
    territory: 'West',
    tenure_months: 48,
    ramp_status: 'veteran',
    active_account_count: 15,
    pipeline_value: 2_340_000,
    capacity_score: 38,
    created_at: '2023-06-01T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
];

// ============================================================
// ACCOUNTS
// ============================================================
export const mockAccounts: Account[] = [
  {
    id: 'acc-001',
    org_id: 'org-001',
    crm_id: 'SF-A001',
    name: 'Meridian Health Systems',
    industry: 'Healthcare',
    employee_count: 2400,
    annual_revenue: 580_000_000,
    website: 'https://meridianhealthsys.com',
    city: 'Chicago',
    state: 'IL',
    country: 'US',
    tech_stack: ['Salesforce', 'Workday', 'Epic'],
    owner_rep_id: 'rep-002',
    last_activity_at: '2026-03-25T14:30:00Z',
    crm_source: 'salesforce',
    raw_data: {},
    created_at: '2024-06-10T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'acc-002',
    org_id: 'org-001',
    crm_id: 'SF-A002',
    name: 'NovaPay Financial',
    industry: 'FinTech',
    employee_count: 850,
    annual_revenue: 120_000_000,
    website: 'https://novapay.io',
    city: 'San Francisco',
    state: 'CA',
    country: 'US',
    tech_stack: ['AWS', 'Stripe', 'Snowflake', 'Salesforce'],
    owner_rep_id: 'rep-001',
    last_activity_at: '2026-03-20T09:15:00Z',
    crm_source: 'salesforce',
    raw_data: {},
    created_at: '2024-09-01T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'acc-003',
    org_id: 'org-001',
    crm_id: 'SF-A003',
    name: 'Cascade Logistics',
    industry: 'Logistics',
    employee_count: 3200,
    annual_revenue: 890_000_000,
    website: 'https://cascadelogistics.com',
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    tech_stack: ['SAP', 'Oracle', 'Salesforce'],
    owner_rep_id: 'rep-004',
    last_activity_at: '2026-01-10T16:00:00Z',
    crm_source: 'salesforce',
    raw_data: {},
    created_at: '2024-03-15T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'acc-004',
    org_id: 'org-001',
    crm_id: 'SF-A004',
    name: 'BrightLoop SaaS',
    industry: 'SaaS',
    employee_count: 320,
    annual_revenue: 45_000_000,
    website: 'https://brightloop.io',
    city: 'Austin',
    state: 'TX',
    country: 'US',
    tech_stack: ['AWS', 'HubSpot', 'Segment', 'Snowflake'],
    owner_rep_id: 'rep-003',
    last_activity_at: '2026-03-27T11:00:00Z',
    crm_source: 'salesforce',
    raw_data: {},
    created_at: '2025-01-20T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'acc-005',
    org_id: 'org-001',
    crm_id: 'SF-A005',
    name: 'Ironclad Manufacturing',
    industry: 'Manufacturing',
    employee_count: 5100,
    annual_revenue: 1_200_000_000,
    website: 'https://ironcladmfg.com',
    city: 'Detroit',
    state: 'MI',
    country: 'US',
    tech_stack: ['SAP', 'Salesforce', 'ServiceNow'],
    owner_rep_id: 'rep-004',
    last_activity_at: '2025-11-05T10:00:00Z',
    crm_source: 'salesforce',
    raw_data: {},
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'acc-006',
    org_id: 'org-001',
    crm_id: 'SF-A006',
    name: 'Vela Commerce',
    industry: 'E-commerce',
    employee_count: 180,
    annual_revenue: 28_000_000,
    website: 'https://velacommerce.com',
    city: 'New York',
    state: 'NY',
    country: 'US',
    tech_stack: ['Shopify', 'AWS', 'Segment'],
    owner_rep_id: 'rep-003',
    last_activity_at: '2026-03-15T08:30:00Z',
    crm_source: 'salesforce',
    raw_data: {},
    created_at: '2025-06-01T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'acc-007',
    org_id: 'org-001',
    crm_id: 'SF-A007',
    name: 'TrueNorth Insurance',
    industry: 'Insurance',
    employee_count: 1800,
    annual_revenue: 340_000_000,
    website: 'https://truenorthins.com',
    city: 'Hartford',
    state: 'CT',
    country: 'US',
    tech_stack: ['Guidewire', 'Salesforce', 'AWS'],
    owner_rep_id: 'rep-002',
    last_activity_at: '2025-12-20T14:00:00Z',
    crm_source: 'salesforce',
    raw_data: {},
    created_at: '2024-08-10T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'acc-008',
    org_id: 'org-001',
    crm_id: 'SF-A008',
    name: 'Quantum Analytics',
    industry: 'SaaS',
    employee_count: 600,
    annual_revenue: 75_000_000,
    website: 'https://quantumanalytics.ai',
    city: 'Boston',
    state: 'MA',
    country: 'US',
    tech_stack: ['Snowflake', 'AWS', 'Salesforce', 'dbt'],
    owner_rep_id: null,
    last_activity_at: null,
    crm_source: 'salesforce',
    raw_data: {},
    created_at: '2025-11-01T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'acc-009',
    org_id: 'org-001',
    crm_id: 'SF-A009',
    name: 'Greenfield Energy',
    industry: 'Energy',
    employee_count: 4500,
    annual_revenue: 960_000_000,
    website: 'https://greenfieldenergy.com',
    city: 'Houston',
    state: 'TX',
    country: 'US',
    tech_stack: ['SAP', 'Oracle', 'Salesforce'],
    owner_rep_id: 'rep-001',
    last_activity_at: '2025-09-15T12:00:00Z',
    crm_source: 'salesforce',
    raw_data: {},
    created_at: '2024-04-20T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
  {
    id: 'acc-010',
    org_id: 'org-001',
    crm_id: 'SF-A010',
    name: 'PulsePoint Media',
    industry: 'AdTech',
    employee_count: 95,
    annual_revenue: 12_000_000,
    website: 'https://pulsepointmedia.com',
    city: 'Los Angeles',
    state: 'CA',
    country: 'US',
    tech_stack: ['GCP', 'HubSpot'],
    owner_rep_id: 'rep-003',
    last_activity_at: '2026-02-28T16:45:00Z',
    crm_source: 'salesforce',
    raw_data: {},
    created_at: '2025-09-15T00:00:00Z',
    updated_at: '2026-03-28T00:00:00Z',
  },
];

// ============================================================
// ACCOUNT SCORES
// ============================================================
export const mockAccountScores: AccountScore[] = [
  {
    id: 'score-001', org_id: 'org-001', account_id: 'acc-001', icp_model_id: 'icp-001',
    total_score: 92,
    components: { firmographic_fit: 95, technographic_fit: 80, intent_signals: 85, hiring_signals: 70, engagement_recency: 100, growth_indicators: 75 },
    explanation: { summary: 'Strong ICP match — healthcare vertical, 2400 employees in ideal range, recent Salesforce and Workday stack signals high tech maturity.', drivers: [{ signal: 'Industry match', impact: 'high', detail: 'Healthcare is top-performing vertical' }, { signal: 'Active engagement', impact: 'high', detail: 'Activity within last 7 days' }] },
    scored_at: '2026-03-28T06:00:00Z',
  },
  {
    id: 'score-002', org_id: 'org-001', account_id: 'acc-002', icp_model_id: 'icp-001',
    total_score: 88,
    components: { firmographic_fit: 85, technographic_fit: 92, intent_signals: 78, hiring_signals: 65, engagement_recency: 80, growth_indicators: 90 },
    explanation: { summary: 'Excellent tech stack alignment with Snowflake and AWS. FinTech vertical is second-highest win rate. Strong growth signals from recent Series C.', drivers: [{ signal: 'Tech stack match', impact: 'high', detail: '4/4 stack components match ICP' }, { signal: 'Growth stage', impact: 'medium', detail: 'Recent funding round' }] },
    scored_at: '2026-03-28T06:00:00Z',
  },
  {
    id: 'score-003', org_id: 'org-001', account_id: 'acc-004', icp_model_id: 'icp-001',
    total_score: 85,
    components: { firmographic_fit: 78, technographic_fit: 88, intent_signals: 72, hiring_signals: 80, engagement_recency: 100, growth_indicators: 85 },
    explanation: { summary: 'SaaS vertical, strong tech stack overlap, and active engagement. Slightly below ideal employee count but rapid growth trajectory compensates.', drivers: [{ signal: 'SaaS vertical', impact: 'high', detail: 'Top win-rate vertical' }, { signal: 'Hiring signals', impact: 'medium', detail: '15 open engineering roles' }] },
    scored_at: '2026-03-28T06:00:00Z',
  },
  {
    id: 'score-004', org_id: 'org-001', account_id: 'acc-005', icp_model_id: 'icp-001',
    total_score: 71,
    components: { firmographic_fit: 82, technographic_fit: 65, intent_signals: 45, hiring_signals: 30, engagement_recency: 20, growth_indicators: 40 },
    explanation: { summary: 'Large manufacturing account with SAP stack. Score dragged down by 5+ months of inactivity and low intent signals. High potential if re-engaged.', drivers: [{ signal: 'Stale engagement', impact: 'high', detail: 'No activity since Nov 2025' }, { signal: 'Size fit', impact: 'medium', detail: '5100 employees in enterprise range' }] },
    scored_at: '2026-03-28T06:00:00Z',
  },
  {
    id: 'score-005', org_id: 'org-001', account_id: 'acc-003', icp_model_id: 'icp-001',
    total_score: 76,
    components: { firmographic_fit: 88, technographic_fit: 70, intent_signals: 55, hiring_signals: 40, engagement_recency: 40, growth_indicators: 60 },
    explanation: { summary: 'Large logistics enterprise with strong firmographic fit. Engagement has gone stale — last activity in January. SAP/Oracle stack partially aligns.', drivers: [{ signal: 'Firmographic fit', impact: 'high', detail: '3200 employees, $890M revenue' }, { signal: 'Stale activity', impact: 'medium', detail: '80+ days since last touch' }] },
    scored_at: '2026-03-28T06:00:00Z',
  },
  {
    id: 'score-006', org_id: 'org-001', account_id: 'acc-007', icp_model_id: 'icp-001',
    total_score: 68,
    components: { firmographic_fit: 80, technographic_fit: 60, intent_signals: 50, hiring_signals: 35, engagement_recency: 30, growth_indicators: 45 },
    explanation: { summary: 'Insurance vertical with Guidewire stack — niche but historically strong close rate. 100+ days without activity is a risk.', drivers: [{ signal: 'Vertical history', impact: 'medium', detail: 'Insurance has 40% win rate' }, { signal: 'Engagement gap', impact: 'high', detail: 'Last activity Dec 2025' }] },
    scored_at: '2026-03-28T06:00:00Z',
  },
  {
    id: 'score-007', org_id: 'org-001', account_id: 'acc-008', icp_model_id: 'icp-001',
    total_score: 82,
    components: { firmographic_fit: 80, technographic_fit: 90, intent_signals: 70, hiring_signals: 75, engagement_recency: 0, growth_indicators: 80 },
    explanation: { summary: 'Unassigned SaaS account with excellent tech stack alignment. No CRM activity yet — net-new opportunity. 600 employees, $75M revenue fits mid-market sweet spot.', drivers: [{ signal: 'Unassigned', impact: 'high', detail: 'No rep coverage' }, { signal: 'Tech alignment', impact: 'high', detail: 'Snowflake + dbt + AWS' }] },
    scored_at: '2026-03-28T06:00:00Z',
  },
  {
    id: 'score-008', org_id: 'org-001', account_id: 'acc-009', icp_model_id: 'icp-001',
    total_score: 45,
    components: { firmographic_fit: 60, technographic_fit: 50, intent_signals: 20, hiring_signals: 15, engagement_recency: 10, growth_indicators: 30 },
    explanation: { summary: 'Energy vertical is outside core ICP. Large account but low intent signals and 6+ months without activity. Current rep capacity is already constrained.', drivers: [{ signal: 'Off-ICP vertical', impact: 'high', detail: 'Energy not in top 5 verticals' }, { signal: 'Very stale', impact: 'high', detail: '200+ days inactive' }] },
    scored_at: '2026-03-28T06:00:00Z',
  },
  {
    id: 'score-009', org_id: 'org-001', account_id: 'acc-006', icp_model_id: 'icp-001',
    total_score: 62,
    components: { firmographic_fit: 55, technographic_fit: 65, intent_signals: 50, hiring_signals: 45, engagement_recency: 80, growth_indicators: 60 },
    explanation: { summary: 'Small e-commerce account. Below ideal size range but active engagement and decent tech stack. Better fit for SMB segment.', drivers: [{ signal: 'Size below ICP', impact: 'medium', detail: '180 employees, $28M revenue' }, { signal: 'Active', impact: 'medium', detail: 'Recent engagement' }] },
    scored_at: '2026-03-28T06:00:00Z',
  },
  {
    id: 'score-010', org_id: 'org-001', account_id: 'acc-010', icp_model_id: 'icp-001',
    total_score: 22,
    components: { firmographic_fit: 25, technographic_fit: 30, intent_signals: 10, hiring_signals: 5, engagement_recency: 60, growth_indicators: 15 },
    explanation: { summary: 'Very small AdTech account — 95 employees, $12M revenue. Well below ICP thresholds. Minimal tech stack overlap. Consuming rep capacity with low conversion probability.', drivers: [{ signal: 'Size mismatch', impact: 'high', detail: 'Far below ICP minimum' }, { signal: 'Low signals', impact: 'high', detail: 'No intent or hiring activity' }] },
    scored_at: '2026-03-28T06:00:00Z',
  },
];

// ============================================================
// RECOMMENDATIONS
// ============================================================
export const mockRecommendations: Recommendation[] = [
  {
    id: 'rec-001',
    org_id: 'org-001',
    type: 'RE_ENGAGE',
    account_id: 'acc-005',
    current_rep_id: 'rep-004',
    recommended_rep_id: null,
    confidence_score: 87,
    reasoning: 'Ironclad Manufacturing scores 71/100 against your ICP but has had zero activity since November 2025 — over 4 months of silence on a $1.2B enterprise account. David Kim currently owns this account but is at 38% capacity with $2.3M in active pipeline. A structured re-engagement sequence targeting their SAP modernization initiative could reopen this opportunity.',
    supporting_data: { days_stale: 148, score: 71 },
    status: 'pending',
    dismissed_reason: null,
    acted_by: null,
    acted_at: null,
    expires_at: '2026-04-09T00:00:00Z',
    created_at: '2026-03-28T06:30:00Z',
  },
  {
    id: 'rec-002',
    org_id: 'org-001',
    type: 'ADD_TO_TERRITORY',
    account_id: 'acc-008',
    current_rep_id: null,
    recommended_rep_id: 'rep-003',
    confidence_score: 91,
    reasoning: 'Quantum Analytics is an unassigned SaaS account scoring 82/100 with excellent Snowflake + dbt + AWS stack alignment. At 600 employees and $75M revenue, it fits squarely in the mid-market sweet spot. Priya Patel has 82% capacity available and strong SaaS vertical expertise — she is the ideal rep to open this account.',
    supporting_data: { score: 82, rep_capacity: 82, tech_overlap: 4 },
    status: 'pending',
    dismissed_reason: null,
    acted_by: null,
    acted_at: null,
    expires_at: '2026-04-09T00:00:00Z',
    created_at: '2026-03-28T06:30:00Z',
  },
  {
    id: 'rec-003',
    org_id: 'org-001',
    type: 'RETIRE',
    account_id: 'acc-010',
    current_rep_id: 'rep-003',
    recommended_rep_id: null,
    confidence_score: 84,
    reasoning: 'PulsePoint Media scores just 22/100 — far below ICP on every dimension. At 95 employees and $12M revenue with minimal tech stack overlap, this account has near-zero conversion probability. Retiring it from Priya Patel\'s territory frees capacity for higher-value targets like Quantum Analytics.',
    supporting_data: { score: 22 },
    status: 'pending',
    dismissed_reason: null,
    acted_by: null,
    acted_at: null,
    expires_at: '2026-04-09T00:00:00Z',
    created_at: '2026-03-28T06:30:00Z',
  },
  {
    id: 'rec-004',
    org_id: 'org-001',
    type: 'REASSIGN',
    account_id: 'acc-007',
    current_rep_id: 'rep-002',
    recommended_rep_id: 'rep-001',
    confidence_score: 72,
    reasoning: 'TrueNorth Insurance has been inactive for 100+ days under Marcus Johnson. Sarah Chen has deeper insurance vertical experience and a 45% win rate in similar accounts. While Sarah\'s capacity is tighter at 42%, the $340M revenue potential justifies the reassignment given Marcus\'s current overload at 24 active accounts.',
    supporting_data: { days_stale: 103, current_rep_accounts: 24, recommended_rep_win_rate: 0.45 },
    status: 'pending',
    dismissed_reason: null,
    acted_by: null,
    acted_at: null,
    expires_at: '2026-04-09T00:00:00Z',
    created_at: '2026-03-28T06:30:00Z',
  },
  {
    id: 'rec-005',
    org_id: 'org-001',
    type: 'RE_ENGAGE',
    account_id: 'acc-003',
    current_rep_id: 'rep-004',
    recommended_rep_id: null,
    confidence_score: 78,
    reasoning: 'Cascade Logistics scores 76/100 and is a $890M enterprise account that has gone cold since January. With 3200 employees and an SAP/Oracle stack, it matches the manufacturing/logistics ICP profile. David Kim should prioritize a re-engagement touchpoint before this account drifts further.',
    supporting_data: { days_stale: 82, score: 76 },
    status: 'pending',
    dismissed_reason: null,
    acted_by: null,
    acted_at: null,
    expires_at: '2026-04-09T00:00:00Z',
    created_at: '2026-03-28T06:30:00Z',
  },
  {
    id: 'rec-006',
    org_id: 'org-001',
    type: 'RETIRE',
    account_id: 'acc-009',
    current_rep_id: 'rep-001',
    recommended_rep_id: null,
    confidence_score: 80,
    reasoning: 'Greenfield Energy scores 45/100 — the energy vertical is outside your core ICP with low intent signals and 200+ days of inactivity. Sarah Chen\'s capacity is already constrained at 42%. Removing this $960M account frees bandwidth for higher-probability deals in her FinTech and SaaS sweet spot.',
    supporting_data: { score: 45, days_stale: 200 },
    status: 'approved',
    dismissed_reason: null,
    acted_by: 'user-001',
    acted_at: '2026-03-29T10:00:00Z',
    expires_at: '2026-04-09T00:00:00Z',
    created_at: '2026-03-28T06:30:00Z',
  },
];

// ============================================================
// OPPORTUNITIES (historical)
// ============================================================
export const mockOpportunities: Opportunity[] = [
  { id: 'opp-001', org_id: 'org-001', crm_id: 'SF-O001', account_id: 'acc-001', rep_id: 'rep-002', name: 'Meridian Platform Deal', amount: 285000, stage: 'Closed Won', status: 'won', close_date: '2025-11-15T00:00:00Z', industry: 'Healthcare', deal_size_bucket: 'large', sales_cycle_days: 92, attributes: {}, created_at: '2025-08-15T00:00:00Z', updated_at: '2025-11-15T00:00:00Z' },
  { id: 'opp-002', org_id: 'org-001', crm_id: 'SF-O002', account_id: 'acc-002', rep_id: 'rep-001', name: 'NovaPay Enterprise License', amount: 420000, stage: 'Negotiation', status: 'open', close_date: '2026-04-30T00:00:00Z', industry: 'FinTech', deal_size_bucket: 'large', sales_cycle_days: 78, attributes: {}, created_at: '2026-01-15T00:00:00Z', updated_at: '2026-03-28T00:00:00Z' },
  { id: 'opp-003', org_id: 'org-001', crm_id: 'SF-O003', account_id: 'acc-004', rep_id: 'rep-003', name: 'BrightLoop Expansion', amount: 95000, stage: 'Proposal', status: 'open', close_date: '2026-05-15T00:00:00Z', industry: 'SaaS', deal_size_bucket: 'medium', sales_cycle_days: 45, attributes: {}, created_at: '2026-02-10T00:00:00Z', updated_at: '2026-03-28T00:00:00Z' },
  { id: 'opp-004', org_id: 'org-001', crm_id: 'SF-O004', account_id: 'acc-006', rep_id: 'rep-003', name: 'Vela Commerce Starter', amount: 35000, stage: 'Discovery', status: 'open', close_date: '2026-06-01T00:00:00Z', industry: 'E-commerce', deal_size_bucket: 'small', sales_cycle_days: 30, attributes: {}, created_at: '2026-03-01T00:00:00Z', updated_at: '2026-03-28T00:00:00Z' },
  { id: 'opp-005', org_id: 'org-001', crm_id: 'SF-O005', account_id: 'acc-009', rep_id: 'rep-001', name: 'Greenfield Energy Pilot', amount: 150000, stage: 'Closed Lost', status: 'lost', close_date: '2025-08-20T00:00:00Z', industry: 'Energy', deal_size_bucket: 'large', sales_cycle_days: 120, attributes: { loss_reason: 'Budget freeze' }, created_at: '2025-04-20T00:00:00Z', updated_at: '2025-08-20T00:00:00Z' },
];

// ============================================================
// ICP MODEL
// ============================================================
export const mockICPModel: ICPModel = {
  id: 'icp-001',
  org_id: 'org-001',
  version: 1,
  attributes: {
    industries: [
      { value: 'SaaS', weight: 92 },
      { value: 'FinTech', weight: 88 },
      { value: 'Healthcare', weight: 85 },
      { value: 'Insurance', weight: 72 },
      { value: 'Manufacturing', weight: 68 },
    ],
    employee_range: { min: 200, max: 5000, weight: 80 },
    revenue_range: { min: 30_000_000, max: 1_000_000_000, weight: 80 },
    tech_stack: [
      { value: 'Salesforce', weight: 95 },
      { value: 'AWS', weight: 85 },
      { value: 'Snowflake', weight: 82 },
      { value: 'Workday', weight: 70 },
    ],
    geographies: [
      { value: 'US', weight: 90 },
    ],
    growth_signals: [
      { value: 'Recent funding', weight: 85 },
      { value: 'Headcount growth >20%', weight: 78 },
    ],
  },
  narrative: 'Your ideal customer is a mid-market to enterprise SaaS or FinTech company with 200–5,000 employees and $30M–$1B in annual revenue, based primarily in the US. They run Salesforce as their CRM with a modern data stack (AWS, Snowflake) and are in an active growth phase — recent funding rounds or 20%+ headcount growth are strong positive indicators. Healthcare and insurance verticals also convert well when the account has Workday or similar HR tech in their stack.',
  created_at: '2026-03-28T05:00:00Z',
};

// ============================================================
// REP-ACCOUNT FIT (sample)
// ============================================================
export const mockRepAccountFit: RepAccountFit[] = [
  { id: 'fit-001', org_id: 'org-001', rep_id: 'rep-003', account_id: 'acc-008', fit_score: 91, rationale: 'Priya has SaaS vertical expertise, 82% capacity available, and East territory alignment with Boston-based Quantum Analytics.', factors: { segment_match: 100, vertical_match: 100, win_rate_relevance: 75, capacity_score: 82, relationship_history: 50, territory_alignment: 100 }, computed_at: '2026-03-28T06:00:00Z' },
  { id: 'fit-002', org_id: 'org-001', rep_id: 'rep-001', account_id: 'acc-008', fit_score: 68, rationale: 'Sarah has SaaS experience but is at 42% capacity and West territory — geographic mismatch.', factors: { segment_match: 100, vertical_match: 100, win_rate_relevance: 80, capacity_score: 42, relationship_history: 50, territory_alignment: 30 }, computed_at: '2026-03-28T06:00:00Z' },
];

// ============================================================
// HELPERS
// ============================================================
export function getAccountById(id: string): Account | undefined {
  return mockAccounts.find(a => a.id === id);
}

export function getRepById(id: string): Rep | undefined {
  return mockReps.find(r => r.id === id);
}

export function getScoreForAccount(accountId: string): AccountScore | undefined {
  return mockAccountScores.find(s => s.account_id === accountId);
}

export function getRepForAccount(accountId: string): Rep | undefined {
  const account = getAccountById(accountId);
  if (!account?.owner_rep_id) return undefined;
  return getRepById(account.owner_rep_id);
}
